#!/bin/bash

github_url="https://github.com/MLforAll"

if [ "$PWD" != "$PROJPATH" ]; then
	read -p "Are you sure you want to clone this here? (yes/no) " sureclone
	if [ "$sureclone" == "no" ]; then
		exit 0
	fi
fi

if [ -d "$1/.git" ]; then
	echo "A git repo already exists with that name!"
	exit 1
fi
if [ -d "$1" ]; then
	echo "A folder exists with that name but doesn't appear to be git"
	read -p "Do you want to attempt cloning? (yes/no) " stillclone
	if [ "$stillclone" == "no" ]; then
		exit 0
	fi
fi

git clone "$github_url/42$1" "$1"
