#!/bin/sh

[ ! -z "$1" -a ! -z "$2" ] || {
	echo "usage: $(basename "$0") domain ip"
	exit 1
}

printf '\033[1;33m%s\033[0m' pending

run=1
while ! host "$1" | grep -F "$2" >/dev/null
do
	printf '\r\033[K\033[1;31m%s\033[0m' "not ok (run $run)"
	sleep 10
	(( run++ ))
done

printf '\r\033[K\033[1;32m%s\033[0m\n' OKAY
host "$1"
