#!/bin/sh

if [ "$1" != "" ]; then
	processName="$1"
else
	echo "usage: $0 running_process [interval]"
	exit 1
fi

if [ "$2" != "" ]; then
	updInterval=$2
else
	updInterval=1
fi

while true
do
	clear
	echo "Watching process \`\`$processName'' every $updInterval second(s)"
	leaks "$processName"
	sleep $updInterval
done
