#!/bin/sh
startdir="."
[ ! -z $1 ] && startdir="$1"
files=`find "$startdir" -type f \( -name "*.c" -o -name "*.h" \)`
[ -f "$startdir/.oproj_config" ] && files=`echo "$files" | grep -v "$(cat "$startdir/.oproj_config")"`
sublopen $files
