#!/bin/bash

byebye()
{
	[ -z "$1" ] || echo
	echo 'Byebye'
	echo
	exit 0
}

trap 'byebye 1' INT

git add -A
echo

git status
echo

read -e -p "Message or \`\`abort'': " msg
[ "$msg" = abort ] && byebye

if [ "$msg" = edit ]
then
	git commit
else
	git commit -m "$msg"
fi
echo

git push
