#!/bin/sh

if [ ! -f "$1" ] && [ ! -d "$1" ]; then
	echo "$(basename "$0"): Error no. 2: No such file or directory!"
	exit 1
fi

sublimePath="$HOME/Applications/Sublime Text.app"
if [ ! -d "$sublimePath" ]; then
	sublimePath='/Applications/Sublime Text.app'
fi

num=$#
cmd="open -a '$sublimePath'"
for (( i=0; i<$num; i++ ))
do
	cmd+=" \"$1\""
	shift
done
eval "$cmd"
