#!/bin/sh

if [ ! -f "$1" ] && [ ! -d "$1" ]; then
	echo "Error no. 2: No such file or directory!"
	exit 1
fi

sublimePath="$HOME/Applications/Sublime Text.app"
if [ ! -d "$sublimePath" ]; then
	sublimePath="/Applications/Sublime Text.app"
fi

cmd="open -a '$sublimePath'"
for (( i=0; i<=$#; i++ ))
do
	cmd+=" \"$1\""
	shift
done
eval "$cmd"
