#!/bin/bash

updall_dir()
{
	local should_disp=1
	local disp_dir="$1"
	[ $disp_dir = '.' ] && disp_dir="$PWD"

	# For Recursive
	local dirs=()

	for p in $1/*
	do
		[ -d "$p" -a ! -d "$p/.git" ] && dirs+=("$p")

		if [ ! -d "$p/.git" ]; then
			continue
		fi

		if [ $should_disp -eq 1 ]
		then
			printf "\033[1;36mOpen dir: $disp_dir\033[0;39m\n"
			should_disp=0
		fi

		echo
		echo "Updating project: $p"
		git -C "$p" pull
	done

	printf "\033[1;36mClose dir: $disp_dir\033[0;39m\n"
	# If recursive mode is not enabled, we stop there
	[ "$2" != recursive ] && return 0

	# Loop thru all folders we saw that aren't git repos
	# Call ourselves one more time
	for rec in "${dirs[@]}"
	do
		[ $should_disp -eq 0 ] && echo
		updall_dir "$rec" $2
	done
}

[ "$1" = '-r' ] && RECURSIVE=recursive

updall_dir . $RECURSIVE
