#!/bin/sh

fatal()
{
	echo "\033[1;39m$1\033[0;39m" 1>&2
	[ -z "$2" ] && exit 1
	exit $2
}

my_path=$(which updcustomcmds)
[ -z "$my_path" ] && fatal 'my_path cannot be empty!'
ccpath=$(dirname "$my_path")

[ -d "$ccpath" ] || fatal "$ccpath not found!"

echo "\033[1;32mUpdating custom_cmds at '$ccpath'\033[0;39m"
git -C "$ccpath" pull
