#!/bin/sh

fatal()
{
	printf "\033[1;39m%s\033[0;39m\n" "$1" >&2
	[ -z "$2" ] && exit 1
	exit $2
}

my_path=$(which updcustomcmds)
[ -z "$my_path" ] && fatal 'my_path cannot be empty!'
ccpath=$(dirname "$my_path")

[ -d "$ccpath" ] || fatal "$ccpath not found!"

printf "\033[1;32m%s\033[0;39m\n" "Updating custom_cmds at '$ccpath'"
git -C "$ccpath" pull
