#!/bin/sh

fatal()
{
	echo "$1"
	exit 1	
}

klist &> /dev/null
if [ $? -ne 0 ]; then
	echo "=============="
	echo "kinit required"
	if [ "$USER42" != "" ]; then
		kusername="$USER42"
	else
		read -p "Enter username @42.FR: " kusername
	fi
	kinit "$kusername"
	if [ $? -ne 0 ]; then
		echo "  kinit fail"
		echo "=============="
		exit 1
	fi
	echo "  kinit done"
	echo "=============="
fi

git add . || fatal "Error with git add"
echo "git add done!"
git status

read -p "Commit msg: " cmsg
git commit -m "$cmsg" || fatal "Error with git commit"
echo "git commit done!"

git push || fatal "Error with git push"
echo "git push done!"
