#!/bin/sh

if [ ! -d "$PROJPATH" ]; then
	echo "$0: missing \$PROJPATH env var"
	exit 1
fi
if [ ! -d "$PROJPATH/Libft" -o ! -d "$PROJPATH/Get_Next_Line" ]; then
	echo "$0: missing Libft or Get_Next_Line folder in \$PROJPATH"
	exit 1
fi
if [ ! -d "$1" -o -z "$2" ]; then
	echo "usage: $0 source destination"
	exit 1
fi

[ ! -d "$2" ] && mkdir "$2"
rm -rf "$2/"*

echo "Copying main project"
cp -a "$1"/* "$2"
echo "Cleaning main project"
rm -f "$2/README.md" "$2/libft"
rm -rf "$2/misc"

echo "Adding libft"
cp -a "$PROJPATH/Libft" "$2/libft"
echo "Cleaning libft"
rm -rf "$2/libft/.git" "$2/libft/misc" "$2/libft/objs"
rm -f "$2/libft/README.md" "$2/libft/auteur" "$2/libft/.oproj_config"
make fclean -C "$2/libft" >/dev/null

if [ -d "$1"/libftreadline ]; then
	echo "Adding libftreadline"
	rm -f "$2/libftreadline"
	cp -a "$PROJPATH/libftreadline" "$2"
	echo "Cleaning libftreadline"
	rm -rf "$2/libftreadline/.git" "$2/libftreadline/misc" "$2/libftreadline/man" "$2/libftreadline/objs"
	rm -f "$2/libftreadline/README.md" "$2/libftreadline/libft" "$2/libftreadline/.oproj_config"
	ln -s ../libft "$2/libftreadline"
	make fclean -C "$2/libftreadline" >/dev/null
fi

echo "Done!"
exit 0
