#!/bin/sh

fatal()
{
	echo "$1"
	exit 1	
}

if [ -d "$1" ]; then
	echo "[INFO] Changing directory to: $1"
	cd "$1"
fi

klist &> /dev/null
if [ $? -ne 0 ]; then
	echo "\033[1;39m==============\033[0;39m"
	echo "kinit required"
	if [ "$USER42" != "" ]; then
		kusername="$USER42"
	else
		read -p "Enter username @42.FR: " kusername
	fi
	kinit "$kusername"
	if [ $? -ne 0 ]; then
		echo "\033[0;31mkinit fail\033[0;39m"
		echo "\033[1;39m==============\033[0;39m"
		exit 1
	fi
	echo "\033[0;33mkinit success\033[0;39m"
	echo "=============="
fi

git add . || fatal "Error with git add"
echo "git add done!"
git status

read -p "Commit msg: " cmsg
git commit -m "$cmsg" || fatal "Error with git commit"
echo "git commit done!"

git push || fatal "Error with git push"
echo "git push done!"
