#!/bin/sh

[ ! -z "$1" ] || { echo 'usage: appid app_name' >&2; exit 1; }

osascript -e "id of application \"$1\"" 2>/dev/null
exval=$?

if [ $exval -ne 0 ]
then
	echo "$1: No such app"
	exit $exval
fi
