#!/bin/sh

fatal()
{
	echo "$1" >&2
	exit 1
}

[ $(id -u) -eq 0 ] || fatal 'This tool must be run as root'

sudoPath=/etc/pam.d/sudo
sudocPath=/etc/pam.d/sudo_custom
if [ -f "$sudocPath" ]
then
	echo '==> Replacing sudo pam service'
	rm -f "$sudoPath"
	ln -s "$sudocPath" "$sudoPath"
fi

bakbashPath=/usr/local/bin/bash
bashPath=/bin/bash
if [ -f "$bakbashPath" ]
then
	echo '==> Replacing bash'
	if diff "$bashPath" "$bakbashPath" >/dev/null 2>&1
	then
		echo "$bakbashPath and $bashPath are identical..."
	else
		mount -uw / || fatal 'Could not remount rootfs'
		rm -f "$bashPath"
		cp "$bakbashPath" "$bashPath"
		chown root:wheel "$bashPath"
		chmod 0555 "$bashPath"
	fi
fi

catalinaLS=/Library/CatalinaLockscreen.jpg
loginuikit=/System/Library/PrivateFrameworks/LoginUIKit.framework/Versions/A/LoginUIKit
if [ -f "$catalinaLS" ]
then
	echo '==> Replacing Lockscreen Picture'
	cp -a "$loginuikit" "${loginuikit}_"
	binstrpatch "$loginuikit" /System/Library/CoreServices/DefaultDesktop.heic "$catalinaLS"
	codesign -f -s - "$loginuikit"
	read -p 'Go to lockscreen to test (requires fus utility) (y/n) ' testfus
	if [ "$testfus" = y -o "$testfus" = Y ]
	then
		fus && sleep 5
		read -p 'Remove backup? (y/n) ' rmbackup
		if [ "$rmbackup" = y -o "$rmbackup" = Y ]
		then
			rm -f "${loginuikit}_"
		fi
	fi
fi
