#!/bin/sh

# Run on macOS check
[ $(uname) = Darwin ] || { echo 'Not running macOS/OS X' >&2; exit 1; }

# Args Pre
noopen=0
if [ "$1" = '-n' ]
then
	noopen=1
	shift
fi

# Create MP
if [ -d /Volumes/ESP ]
then
	read -p "There is already a 'ESP' folder! Now what? (rm/use/open) " ans
	if [ "$ans" = rm ]
	then
		sudo rm -R /Volumes/ESP
	fi
else
	sudo mkdir /Volumes/ESP
fi

# Mount
if [ "$ans" != open ]
then
	devNode="/dev/disk0s1"
	[ -z "$1" ] || devNode="$1"
	sudo mount_msdos "$devNode" /Volumes/ESP
fi

# Open 1/2
openESP=n
if [ $noopen -eq 0 ]
then
	read -p 'Open /Volumes/ESP (y/n) ' openESP
fi

# Open 2/2
if [ "$openESP" = y -o "$openESP" = Y ]
then
	open /Volumes/ESP
else
	echo 'Contents of /Volumes/ESP:'
	ls -lhG /Volumes/ESP
	exit 0
fi
