#!/bin/bash

# FUNC(S)

# Takes 3 args : $1 = msg | $2 = sleepTime | $3 = global $1
errMsgExitCode1 ()
{
	echo "$1"
	echo 'Aborting...'

	local sleepTime
	if [ -z "$2" ]; then sleepTime="1"; else sleepTime="$2"; fi
	sleep $sleepTime

	[ ! -z "$3" ] || echo

	exit 1
}

# SCRIPT

[ $(uname) = Darwin ] ||
{
	echo 'Not running macOS/OS X' >&2
	exit 1
}

if [ -z "$1" ]; then

	echo
	echo '========================================================'
	echo '     SYSTEM EXTENSION FOLDER FIXER FOR OS X (10.6+)     '
	echo '                    By @MLforAll          			  '
	echo '========================================================'
	echo

	read -p 'Type volume name : ' volumename

else
	volumename="$1"
fi

echo

os_major=$(sw_vers -productVersion | cut -d. -f1)
os_ver=$(sw_vers -productVersion | cut -d. -f2)
if [ $os_ver -lt 12 -a $os_major -eq 10 ]; then
	os_name='OS X'
else
	os_name=macOS
fi

alias sudo='sudo -p "Type your $os_name admin password: "'

if [ "$volumename" = '/' ]
then
	diskutil info -plist / > /tmp/rootVolInfos.plist
	volumename=$(/usr/libexec/PlistBuddy -c 'Print :VolumeName' /tmp/rootVolInfos.plist)
	rm /tmp/rootVolInfos.plist
fi

[ -f "/Volumes/$volumename/System/Library/CoreServices/SystemVersion.plist" ] || errMsgExitCode1 "Invalid input!" 1 "$1"

dest_osmajor=$(/usr/libexec/PlistBuddy -c 'Print :ProductVersion' "/Volumes/$volumename/System/Library/CoreServices/SystemVersion.plist" | cut -d. -f1)
dest_osver=$(/usr/libexec/PlistBuddy -c 'Print :ProductVersion' "/Volumes/$volumename/System/Library/CoreServices/SystemVersion.plist" | cut -d. -f2)
[ $dest_osver -gt 5 -o $dest_osmajor -gt 10 ] || errMsgExitCode1 'This script only works on Mac OS X Snow Leopard (10.6) or newer!' 1 "$1"

if [ \( $os_major -eq 10 -a $os_ver -lt 15 \) -o "$1" != '/' ]
then
	sudo chown -R root:wheel "/Volumes/$volumename/System/Library/Extensions"
	echo '>> CHOWN /S/L/E COMPLETE'

	sudo touch "/Volumes/$volumename/System/Library/Extensions"
	echo '>> TOUCH /S/L/E COMPLETE'
fi

sudo touch "/Volumes/$volumename/Library/Extensions"
echo '>> TOUCH /L/E COMPLETE'
echo

[ -d "/Volumes/$volumename/System/Library/Caches" ] || sudo mkdir "/Volumes/$volumename/System/Library/Caches"
[ -d "/Volumes/$volumename/System/Library/Caches/com.apple.kext.caches" ] || sudo mkdir "/Volumes/$volumename/System/Library/Caches/com.apple.kext.caches"
[ -d "/Volumes/$volumename/System/Library/Caches/com.apple.kext.caches/Startup" ] || sudo mkdir "/Volumes/$volumename/System/Library/Caches/com.apple.kext.caches/Startup"
[ ! -f "/Volumes/$volumename/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache" ] || sudo rm -f "/Volumes/$volumename/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache"

if [ $dest_osmajor -eq 10 -a $dest_osver -lt 15 -a -f "/Volumes/$volumename/System/Library/PrelinkedKernels/prelinkedkernel" ]; then
	sudo rm -f "/Volumes/$volumename/System/Library/PrelinkedKernels/prelinkedkernel"
fi

sudo kextcache -f -update-volume "/Volumes/$volumename"
echo
echo '>> KEXTCACHE COMPLETE'
echo

if [ -z "$1" ]
then
	echo 'Done !'
	echo
	sleep 2
fi
