#!/bin/sh
[ ! -z "$1" ] || { echo 'usage: forceDarkMode app_name' >&2; exit 1; }

bid=$(appid "$1")
[ $? -eq 0 -a ! -z "$bid" ] || { echo 'appid failed!' >&2; exit 2; }

if [ "$2" = revert ]
then
	echo "$bid: revert"
	defaults delete "$bid" NSRequiresAquaSystemAppearance
else
	echo "$bid: force Dark Mode"
	defaults write "$bid" NSRequiresAquaSystemAppearance -bool NO
fi
