#!/bin/bash

BASENAME=$(basename "$0")

OS_VERSION=$(sw_vers -productVersion)
OS_MAJOR=$(echo "$OS_VERSION" | cut -d. -f1)
OS_MINOR=$(echo "$OS_VERSION" | cut -d. -f2)

fatal()
{
	echo "$BASENAME: $1" >&2
	exit 1
}

[ $(id -u) -eq 0 ] || fatal 'This tool must be run as root'

ensureWritableRootFS()
{
	[ -z "$DID_REMOUNT_ROOTFS" ] || return 0

	if [ $OS_MAJOR -eq 10 -a $OS_MINOR -eq 15 ]
	then
		echo 'macOS Catalina: Remounting rootfs'
		mount -uw / || {
			echo 'WARN: Could not remount rootfs' >&2
			exit 1
		}
	fi

	DID_REMOUNT_ROOTFS=1
}

sudoPatch()
{
	local sudoPath=/etc/pam.d/sudo
	local sudocPath=/etc/pam.d/sudo_custom
	[ -f "$sudocPath" ] || return 0

	echo '==> sudo pam service Patch'

	rm -f "$sudoPath"
	ln -s "$sudocPath" "$sudoPath"
}

bashPatch()
{
	local bakbashPath=/usr/local/bin/bash
	local bashPath=/bin/bash
	[ -f "$bakbashPath" ] || return 0

	echo '==> /bin/bash Patch'

	if [ $OS_MAJOR -gt 10 -o $OS_MINOR -gt 15 ]
	then
		echo 'This patch requires version 10.15 or lower' >&2
		return 1
	fi

	ensureWritableRootFS

	if [ "$SHELL" != '/bin/bash' ]
	then
		echo "\$SHELL indicates a custom shell. Not applying bashPatch..."
		return 0
	fi

	if diff "$bashPath" "$bakbashPath" >/dev/null 2>&1
	then
		echo "$bakbashPath and $bashPath are identical..."
		return 0
	fi

	rm -f "$bashPath"
	cp "$bakbashPath" "$bashPath"
	chown root:wheel "$bashPath"
	chmod 0555 "$bashPath"
}

lockscreenPatch()
{
	local lockscreenPicturePath=/Library/DefaultLockscreen.jpg
	local loginuikit=/System/Library/PrivateFrameworks/LoginUIKit.framework/Versions/A/LoginUIKit

	echo '==> Lockscreen Picture Patch'

	if [ $OS_MAJOR -gt 10 -o \( $OS_MINOR -ne 14 -a $OS_MINOR -ne 15 \) ]
	then
		echo 'This patch requires version 10.14 or 10.15' >&2
		return 1
	fi

	ensureWritableRootFS

	if [ ! -f "$lockscreenPicturePath" ]
	then
		echo "$lockscreenPicturePath not found" >&2
		return 0
	fi

	cp -a "$loginuikit" "${loginuikit}_"
	binstrpatch "$loginuikit" /System/Library/CoreServices/DefaultDesktop.heic "$lockscreenPicturePath"
	codesign -f -s - "$loginuikit"
	read -p 'Go to lockscreen to test (requires fus utility) (y/n) ' testfus
	if [ "$testfus" = y -o "$testfus" = Y ]
	then
		fus && sleep 5
		read -p 'Remove backup? (y/n) ' rmbackup
		if [ "$rmbackup" = y -o "$rmbackup" = Y ]
		then
			rm -f "${loginuikit}_"
		fi
	fi
}

patches=(sudoPatch bashPatch lockscreenPatch)
firstPatch=0
for p in "${patches[@]}"
do
	if [ $firstPatch -eq 0 ]
	then
		firstPatch=1
	else
		echo
	fi
	"$p"
done
