#!/bin/sh

if [ ! -z "$1" ]
then
	cd "$1" || exit
fi

nworks=$(ls -1d *.xcworkspace 2>/dev/null | wc -l | tr -d ' ')
nprojs=$(ls -1d *.xcodeproj 2>/dev/null | wc -l | tr -d ' ')

if [ $nworks -eq 1 ]
then
	open *.xcworkspace
	exit
fi

case $nprojs in
	0 )
		echo 'No Xcode Project Found' >&2
		exit 1
		;;
	1 )
		break
		;;
	* )
		echo "More than 1 ($nprojs) Xcode Project Found" >&2
		exit 1
		;;
esac

open *.xcodeproj
