#!/bin/sh
[ ! -z "$1" ] || { echo 'usage: forceDarkMode app_name' >&2; exit 1; }

bid=$(appid "$1")
[ $? -eq 0 -a ! -z "$bid" ] || { echo 'appid failed!' >&2; exit 2; }

case "$2" in
	revert )
		echo "$bid: revert"
		defaults delete "$bid" NSRequiresAquaSystemAppearance
		;;
	light )
		echo "$bid: force Light Mode (for badly written apps)"
		defaults write "$bid" NSRequiresAquaSystemAppearance -bool YES
		;;
	'' )
		echo "$bid: force Dark Mode"
		defaults write "$bid" NSRequiresAquaSystemAppearance -bool NO
		;;
	* )
		echo "usage: $(basename "$0") [revert|light]"
		exit 1
		;;
esac
