#!/bin/sh

[ -f "$1" ] || {
	echo "usage: $(basename "$0") /path/to/webloc"
	exit 1
}

url=$(/usr/libexec/PlistBuddy -c 'print :URL' "$1" 2>/dev/null)
[ -n "$url" ] || {
	echo "fatal: $1 is not a valid URl webloc file" >&2
	exit 1
}

echo "$url"
